const swaggerAutogen = require('swagger-autogen')({openapi: '3.0.0'})

const outputFile = './swagger_output.json'
const endpointsFiles = ['./src/index.js']

const doc = {
    info: {
        version: "1.0.0",
        title: "Pizzeria Express",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    definitions: {
        ReqLogin: {
            email: "teste@teste.com.br",
            senha: "12345678",
        },
        ReqUsuario: {
            nome: "Jovenil Pessoa Bento",
            dataNascimento: "14/05/2016",
            enero: "Masculino",
            cpf: "72662964634",
            endereco: {
                logradouro: "Rua Joaquim Carneiro",
                numero: "1",
                cidade: "Magé",
                uf: "RJ",
                cep: "25902-073",
                bairro: "Nova Marília",
                pais: "Brasil"
            },
            email: "jovenil.bento@mail.com.br",
            senha: "ut7&al9lpTfs",
            perfil: "Cliente"

        }
    }
}

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./src/index')           // Your project's root file
})